### ISSUE TITLE
вопрос про прокси

### ISSUE THREAD

**Issue by warzes** [gizmo75rus/HCS#1]
Как запустить если используется прокси соединение?

а то пишет что нет доступа.

**Comment by gizmo75rus** [comment]
Для работы через прокси следует дополнить соответствующий биндинг  в конструкторе класса SoapClientBase  например   _binding.Elements.Add(new HttpsTransportBindingElement {                    ProxyAddress = new Uri("адрес прокси сервера")  }). Также вам потребуется настроить прокси сервер для работы с ГИС ЖКХ.
